// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: anidb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AniDBService_SearchTitles_FullMethodName             = "/kbarr.AniDBService/SearchTitles"
	AniDBService_GetAnimeDetails_FullMethodName          = "/kbarr.AniDBService/GetAnimeDetails"
	AniDBService_PrepareDetailedFromMedia_FullMethodName = "/kbarr.AniDBService/PrepareDetailedFromMedia"
)

// AniDBServiceClient is the client API for AniDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AniDBServiceClient interface {
	SearchTitles(ctx context.Context, in *AniDBSearchTitlesRequest, opts ...grpc.CallOption) (*AniDBSearchTitlesResponse, error)
	GetAnimeDetails(ctx context.Context, in *AniDBGetAnimeDetailsRequest, opts ...grpc.CallOption) (*AniDBAnimeDetails, error)
	PrepareDetailedFromMedia(ctx context.Context, in *AniDBMedia, opts ...grpc.CallOption) (*AniDBDetailed, error)
}

type aniDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAniDBServiceClient(cc grpc.ClientConnInterface) AniDBServiceClient {
	return &aniDBServiceClient{cc}
}

func (c *aniDBServiceClient) SearchTitles(ctx context.Context, in *AniDBSearchTitlesRequest, opts ...grpc.CallOption) (*AniDBSearchTitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AniDBSearchTitlesResponse)
	err := c.cc.Invoke(ctx, AniDBService_SearchTitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aniDBServiceClient) GetAnimeDetails(ctx context.Context, in *AniDBGetAnimeDetailsRequest, opts ...grpc.CallOption) (*AniDBAnimeDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AniDBAnimeDetails)
	err := c.cc.Invoke(ctx, AniDBService_GetAnimeDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aniDBServiceClient) PrepareDetailedFromMedia(ctx context.Context, in *AniDBMedia, opts ...grpc.CallOption) (*AniDBDetailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AniDBDetailed)
	err := c.cc.Invoke(ctx, AniDBService_PrepareDetailedFromMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AniDBServiceServer is the server API for AniDBService service.
// All implementations must embed UnimplementedAniDBServiceServer
// for forward compatibility.
type AniDBServiceServer interface {
	SearchTitles(context.Context, *AniDBSearchTitlesRequest) (*AniDBSearchTitlesResponse, error)
	GetAnimeDetails(context.Context, *AniDBGetAnimeDetailsRequest) (*AniDBAnimeDetails, error)
	PrepareDetailedFromMedia(context.Context, *AniDBMedia) (*AniDBDetailed, error)
	mustEmbedUnimplementedAniDBServiceServer()
}

// UnimplementedAniDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAniDBServiceServer struct{}

func (UnimplementedAniDBServiceServer) SearchTitles(context.Context, *AniDBSearchTitlesRequest) (*AniDBSearchTitlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTitles not implemented")
}
func (UnimplementedAniDBServiceServer) GetAnimeDetails(context.Context, *AniDBGetAnimeDetailsRequest) (*AniDBAnimeDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnimeDetails not implemented")
}
func (UnimplementedAniDBServiceServer) PrepareDetailedFromMedia(context.Context, *AniDBMedia) (*AniDBDetailed, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareDetailedFromMedia not implemented")
}
func (UnimplementedAniDBServiceServer) mustEmbedUnimplementedAniDBServiceServer() {}
func (UnimplementedAniDBServiceServer) testEmbeddedByValue()                      {}

// UnsafeAniDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AniDBServiceServer will
// result in compilation errors.
type UnsafeAniDBServiceServer interface {
	mustEmbedUnimplementedAniDBServiceServer()
}

func RegisterAniDBServiceServer(s grpc.ServiceRegistrar, srv AniDBServiceServer) {
	// If the following call panics, it indicates UnimplementedAniDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AniDBService_ServiceDesc, srv)
}

func _AniDBService_SearchTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AniDBSearchTitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AniDBServiceServer).SearchTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AniDBService_SearchTitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AniDBServiceServer).SearchTitles(ctx, req.(*AniDBSearchTitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AniDBService_GetAnimeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AniDBGetAnimeDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AniDBServiceServer).GetAnimeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AniDBService_GetAnimeDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AniDBServiceServer).GetAnimeDetails(ctx, req.(*AniDBGetAnimeDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AniDBService_PrepareDetailedFromMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AniDBMedia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AniDBServiceServer).PrepareDetailedFromMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AniDBService_PrepareDetailedFromMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AniDBServiceServer).PrepareDetailedFromMedia(ctx, req.(*AniDBMedia))
	}
	return interceptor(ctx, in, info, handler)
}

// AniDBService_ServiceDesc is the grpc.ServiceDesc for AniDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AniDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kbarr.AniDBService",
	HandlerType: (*AniDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchTitles",
			Handler:    _AniDBService_SearchTitles_Handler,
		},
		{
			MethodName: "GetAnimeDetails",
			Handler:    _AniDBService_GetAnimeDetails_Handler,
		},
		{
			MethodName: "PrepareDetailedFromMedia",
			Handler:    _AniDBService_PrepareDetailedFromMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anidb.proto",
}
