// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: anidb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AniDBSearchTitlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBSearchTitlesRequest) Reset() {
	*x = AniDBSearchTitlesRequest{}
	mi := &file_anidb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBSearchTitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBSearchTitlesRequest) ProtoMessage() {}

func (x *AniDBSearchTitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBSearchTitlesRequest.ProtoReflect.Descriptor instead.
func (*AniDBSearchTitlesRequest) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{0}
}

func (x *AniDBSearchTitlesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type AniDBSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           uint64                 `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Added         bool                   `protobuf:"varint,3,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBSearchResult) Reset() {
	*x = AniDBSearchResult{}
	mi := &file_anidb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBSearchResult) ProtoMessage() {}

func (x *AniDBSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBSearchResult.ProtoReflect.Descriptor instead.
func (*AniDBSearchResult) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{1}
}

func (x *AniDBSearchResult) GetAid() uint64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *AniDBSearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AniDBSearchResult) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type AniDBSearchTitlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AniDBSearchResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBSearchTitlesResponse) Reset() {
	*x = AniDBSearchTitlesResponse{}
	mi := &file_anidb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBSearchTitlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBSearchTitlesResponse) ProtoMessage() {}

func (x *AniDBSearchTitlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBSearchTitlesResponse.ProtoReflect.Descriptor instead.
func (*AniDBSearchTitlesResponse) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{2}
}

func (x *AniDBSearchTitlesResponse) GetResults() []*AniDBSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type AniDBGetAnimeDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           uint64                 `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBGetAnimeDetailsRequest) Reset() {
	*x = AniDBGetAnimeDetailsRequest{}
	mi := &file_anidb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBGetAnimeDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBGetAnimeDetailsRequest) ProtoMessage() {}

func (x *AniDBGetAnimeDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBGetAnimeDetailsRequest.ProtoReflect.Descriptor instead.
func (*AniDBGetAnimeDetailsRequest) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{3}
}

func (x *AniDBGetAnimeDetailsRequest) GetAid() uint64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

type AniDBAnimeTitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBAnimeTitle) Reset() {
	*x = AniDBAnimeTitle{}
	mi := &file_anidb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBAnimeTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBAnimeTitle) ProtoMessage() {}

func (x *AniDBAnimeTitle) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBAnimeTitle.ProtoReflect.Descriptor instead.
func (*AniDBAnimeTitle) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{4}
}

func (x *AniDBAnimeTitle) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *AniDBAnimeTitle) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AniDBAnimeTitle) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AniDBRelatedAnime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBRelatedAnime) Reset() {
	*x = AniDBRelatedAnime{}
	mi := &file_anidb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBRelatedAnime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBRelatedAnime) ProtoMessage() {}

func (x *AniDBRelatedAnime) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBRelatedAnime.ProtoReflect.Descriptor instead.
func (*AniDBRelatedAnime) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{5}
}

func (x *AniDBRelatedAnime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AniDBRelatedAnime) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AniDBRelatedAnime) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AniDBSimilarAnime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Approval      string                 `protobuf:"bytes,2,opt,name=approval,proto3" json:"approval,omitempty"`
	Total         string                 `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBSimilarAnime) Reset() {
	*x = AniDBSimilarAnime{}
	mi := &file_anidb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBSimilarAnime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBSimilarAnime) ProtoMessage() {}

func (x *AniDBSimilarAnime) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBSimilarAnime.ProtoReflect.Descriptor instead.
func (*AniDBSimilarAnime) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{6}
}

func (x *AniDBSimilarAnime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AniDBSimilarAnime) GetApproval() string {
	if x != nil {
		return x.Approval
	}
	return ""
}

func (x *AniDBSimilarAnime) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *AniDBSimilarAnime) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AniDBRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBRecommendation) Reset() {
	*x = AniDBRecommendation{}
	mi := &file_anidb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBRecommendation) ProtoMessage() {}

func (x *AniDBRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBRecommendation.ProtoReflect.Descriptor instead.
func (*AniDBRecommendation) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{7}
}

func (x *AniDBRecommendation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AniDBRecommendation) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AniDBRecommendation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AniDBCreator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBCreator) Reset() {
	*x = AniDBCreator{}
	mi := &file_anidb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBCreator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBCreator) ProtoMessage() {}

func (x *AniDBCreator) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBCreator.ProtoReflect.Descriptor instead.
func (*AniDBCreator) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{8}
}

func (x *AniDBCreator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AniDBCreator) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AniDBCreator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AniDBVoteRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Votes         string                 `protobuf:"bytes,1,opt,name=votes,proto3" json:"votes,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBVoteRating) Reset() {
	*x = AniDBVoteRating{}
	mi := &file_anidb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBVoteRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBVoteRating) ProtoMessage() {}

func (x *AniDBVoteRating) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBVoteRating.ProtoReflect.Descriptor instead.
func (*AniDBVoteRating) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{9}
}

func (x *AniDBVoteRating) GetVotes() string {
	if x != nil {
		return x.Votes
	}
	return ""
}

func (x *AniDBVoteRating) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AniDBCountRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         string                 `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBCountRating) Reset() {
	*x = AniDBCountRating{}
	mi := &file_anidb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBCountRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBCountRating) ProtoMessage() {}

func (x *AniDBCountRating) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBCountRating.ProtoReflect.Descriptor instead.
func (*AniDBCountRating) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{10}
}

func (x *AniDBCountRating) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

func (x *AniDBCountRating) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AniDBRatings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permanent     *AniDBCountRating      `protobuf:"bytes,1,opt,name=permanent,proto3" json:"permanent,omitempty"`
	Temporary     *AniDBCountRating      `protobuf:"bytes,2,opt,name=temporary,proto3" json:"temporary,omitempty"`
	Review        *AniDBCountRating      `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBRatings) Reset() {
	*x = AniDBRatings{}
	mi := &file_anidb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBRatings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBRatings) ProtoMessage() {}

func (x *AniDBRatings) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBRatings.ProtoReflect.Descriptor instead.
func (*AniDBRatings) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{11}
}

func (x *AniDBRatings) GetPermanent() *AniDBCountRating {
	if x != nil {
		return x.Permanent
	}
	return nil
}

func (x *AniDBRatings) GetTemporary() *AniDBCountRating {
	if x != nil {
		return x.Temporary
	}
	return nil
}

func (x *AniDBRatings) GetReview() *AniDBCountRating {
	if x != nil {
		return x.Review
	}
	return nil
}

type AniDBResourceExternalEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    []string               `protobuf:"bytes,1,rep,name=identifier,proto3" json:"identifier,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBResourceExternalEntity) Reset() {
	*x = AniDBResourceExternalEntity{}
	mi := &file_anidb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBResourceExternalEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBResourceExternalEntity) ProtoMessage() {}

func (x *AniDBResourceExternalEntity) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBResourceExternalEntity.ProtoReflect.Descriptor instead.
func (*AniDBResourceExternalEntity) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{12}
}

func (x *AniDBResourceExternalEntity) GetIdentifier() []string {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *AniDBResourceExternalEntity) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AniDBResource struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	Type           string                       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ExternalEntity *AniDBResourceExternalEntity `protobuf:"bytes,2,opt,name=external_entity,json=externalEntity,proto3" json:"external_entity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AniDBResource) Reset() {
	*x = AniDBResource{}
	mi := &file_anidb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBResource) ProtoMessage() {}

func (x *AniDBResource) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBResource.ProtoReflect.Descriptor instead.
func (*AniDBResource) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{13}
}

func (x *AniDBResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AniDBResource) GetExternalEntity() *AniDBResourceExternalEntity {
	if x != nil {
		return x.ExternalEntity
	}
	return nil
}

type AniDBTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Weight        string                 `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
	LocalSpoiler  string                 `protobuf:"bytes,4,opt,name=local_spoiler,json=localSpoiler,proto3" json:"local_spoiler,omitempty"`
	GlobalSpoiler string                 `protobuf:"bytes,5,opt,name=global_spoiler,json=globalSpoiler,proto3" json:"global_spoiler,omitempty"`
	Verified      string                 `protobuf:"bytes,6,opt,name=verified,proto3" json:"verified,omitempty"`
	Update        string                 `protobuf:"bytes,7,opt,name=update,proto3" json:"update,omitempty"`
	Infobox       string                 `protobuf:"bytes,8,opt,name=infobox,proto3" json:"infobox,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	PicUrl        string                 `protobuf:"bytes,11,opt,name=pic_url,json=picUrl,proto3" json:"pic_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBTag) Reset() {
	*x = AniDBTag{}
	mi := &file_anidb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBTag) ProtoMessage() {}

func (x *AniDBTag) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBTag.ProtoReflect.Descriptor instead.
func (*AniDBTag) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{14}
}

func (x *AniDBTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AniDBTag) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *AniDBTag) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *AniDBTag) GetLocalSpoiler() string {
	if x != nil {
		return x.LocalSpoiler
	}
	return ""
}

func (x *AniDBTag) GetGlobalSpoiler() string {
	if x != nil {
		return x.GlobalSpoiler
	}
	return ""
}

func (x *AniDBTag) GetVerified() string {
	if x != nil {
		return x.Verified
	}
	return ""
}

func (x *AniDBTag) GetUpdate() string {
	if x != nil {
		return x.Update
	}
	return ""
}

func (x *AniDBTag) GetInfobox() string {
	if x != nil {
		return x.Infobox
	}
	return ""
}

func (x *AniDBTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AniDBTag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AniDBTag) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

type AniDBCharacterType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBCharacterType) Reset() {
	*x = AniDBCharacterType{}
	mi := &file_anidb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBCharacterType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBCharacterType) ProtoMessage() {}

func (x *AniDBCharacterType) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBCharacterType.ProtoReflect.Descriptor instead.
func (*AniDBCharacterType) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{15}
}

func (x *AniDBCharacterType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AniDBCharacterType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AniDBSeiyuu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Picture       string                 `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBSeiyuu) Reset() {
	*x = AniDBSeiyuu{}
	mi := &file_anidb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBSeiyuu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBSeiyuu) ProtoMessage() {}

func (x *AniDBSeiyuu) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBSeiyuu.ProtoReflect.Descriptor instead.
func (*AniDBSeiyuu) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{16}
}

func (x *AniDBSeiyuu) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AniDBSeiyuu) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *AniDBSeiyuu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AniDBCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Update        string                 `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Rating        *AniDBVoteRating       `protobuf:"bytes,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	CharacterType *AniDBCharacterType    `protobuf:"bytes,7,opt,name=character_type,json=characterType,proto3" json:"character_type,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Picture       string                 `protobuf:"bytes,9,opt,name=picture,proto3" json:"picture,omitempty"`
	Seiyuu        []*AniDBSeiyuu         `protobuf:"bytes,10,rep,name=seiyuu,proto3" json:"seiyuu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBCharacter) Reset() {
	*x = AniDBCharacter{}
	mi := &file_anidb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBCharacter) ProtoMessage() {}

func (x *AniDBCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBCharacter.ProtoReflect.Descriptor instead.
func (*AniDBCharacter) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{17}
}

func (x *AniDBCharacter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AniDBCharacter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AniDBCharacter) GetUpdate() string {
	if x != nil {
		return x.Update
	}
	return ""
}

func (x *AniDBCharacter) GetRating() *AniDBVoteRating {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *AniDBCharacter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AniDBCharacter) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *AniDBCharacter) GetCharacterType() *AniDBCharacterType {
	if x != nil {
		return x.CharacterType
	}
	return nil
}

func (x *AniDBCharacter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AniDBCharacter) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *AniDBCharacter) GetSeiyuu() []*AniDBSeiyuu {
	if x != nil {
		return x.Seiyuu
	}
	return nil
}

type AniDBEpisodeNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBEpisodeNumber) Reset() {
	*x = AniDBEpisodeNumber{}
	mi := &file_anidb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBEpisodeNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBEpisodeNumber) ProtoMessage() {}

func (x *AniDBEpisodeNumber) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBEpisodeNumber.ProtoReflect.Descriptor instead.
func (*AniDBEpisodeNumber) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{18}
}

func (x *AniDBEpisodeNumber) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AniDBEpisodeNumber) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AniDBAnimeEpisode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Update        string                 `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	EpNo          *AniDBEpisodeNumber    `protobuf:"bytes,3,opt,name=ep_no,json=epNo,proto3" json:"ep_no,omitempty"`
	Length        string                 `protobuf:"bytes,4,opt,name=length,proto3" json:"length,omitempty"`
	AirDate       string                 `protobuf:"bytes,5,opt,name=air_date,json=airDate,proto3" json:"air_date,omitempty"`
	Rating        *AniDBVoteRating       `protobuf:"bytes,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Titles        []*AniDBAnimeTitle     `protobuf:"bytes,7,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBAnimeEpisode) Reset() {
	*x = AniDBAnimeEpisode{}
	mi := &file_anidb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBAnimeEpisode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBAnimeEpisode) ProtoMessage() {}

func (x *AniDBAnimeEpisode) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBAnimeEpisode.ProtoReflect.Descriptor instead.
func (*AniDBAnimeEpisode) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{19}
}

func (x *AniDBAnimeEpisode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AniDBAnimeEpisode) GetUpdate() string {
	if x != nil {
		return x.Update
	}
	return ""
}

func (x *AniDBAnimeEpisode) GetEpNo() *AniDBEpisodeNumber {
	if x != nil {
		return x.EpNo
	}
	return nil
}

func (x *AniDBAnimeEpisode) GetLength() string {
	if x != nil {
		return x.Length
	}
	return ""
}

func (x *AniDBAnimeEpisode) GetAirDate() string {
	if x != nil {
		return x.AirDate
	}
	return ""
}

func (x *AniDBAnimeEpisode) GetRating() *AniDBVoteRating {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *AniDBAnimeEpisode) GetTitles() []*AniDBAnimeTitle {
	if x != nil {
		return x.Titles
	}
	return nil
}

type AniDBAnimeDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Aid             uint64                 `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Restricted      string                 `protobuf:"bytes,2,opt,name=restricted,proto3" json:"restricted,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	EpisodeCount    int32                  `protobuf:"varint,4,opt,name=episode_count,json=episodeCount,proto3" json:"episode_count,omitempty"`
	StartDate       string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate         string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Titles          []*AniDBAnimeTitle     `protobuf:"bytes,7,rep,name=titles,proto3" json:"titles,omitempty"`
	RelatedAnime    []*AniDBRelatedAnime   `protobuf:"bytes,8,rep,name=related_anime,json=relatedAnime,proto3" json:"related_anime,omitempty"`
	SimilarAnime    []*AniDBSimilarAnime   `protobuf:"bytes,9,rep,name=similar_anime,json=similarAnime,proto3" json:"similar_anime,omitempty"`
	Recommendations []*AniDBRecommendation `protobuf:"bytes,10,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Url             string                 `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Creators        []*AniDBCreator        `protobuf:"bytes,12,rep,name=creators,proto3" json:"creators,omitempty"`
	Description     string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Ratings         *AniDBRatings          `protobuf:"bytes,14,opt,name=ratings,proto3" json:"ratings,omitempty"`
	Picture         string                 `protobuf:"bytes,15,opt,name=picture,proto3" json:"picture,omitempty"`
	Resources       []*AniDBResource       `protobuf:"bytes,16,rep,name=resources,proto3" json:"resources,omitempty"`
	Tags            []*AniDBTag            `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	Episodes        []*AniDBAnimeEpisode   `protobuf:"bytes,18,rep,name=episodes,proto3" json:"episodes,omitempty"`
	Characters      []*AniDBCharacter      `protobuf:"bytes,19,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AniDBAnimeDetails) Reset() {
	*x = AniDBAnimeDetails{}
	mi := &file_anidb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBAnimeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBAnimeDetails) ProtoMessage() {}

func (x *AniDBAnimeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBAnimeDetails.ProtoReflect.Descriptor instead.
func (*AniDBAnimeDetails) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{20}
}

func (x *AniDBAnimeDetails) GetAid() uint64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *AniDBAnimeDetails) GetRestricted() string {
	if x != nil {
		return x.Restricted
	}
	return ""
}

func (x *AniDBAnimeDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AniDBAnimeDetails) GetEpisodeCount() int32 {
	if x != nil {
		return x.EpisodeCount
	}
	return 0
}

func (x *AniDBAnimeDetails) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AniDBAnimeDetails) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *AniDBAnimeDetails) GetTitles() []*AniDBAnimeTitle {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *AniDBAnimeDetails) GetRelatedAnime() []*AniDBRelatedAnime {
	if x != nil {
		return x.RelatedAnime
	}
	return nil
}

func (x *AniDBAnimeDetails) GetSimilarAnime() []*AniDBSimilarAnime {
	if x != nil {
		return x.SimilarAnime
	}
	return nil
}

func (x *AniDBAnimeDetails) GetRecommendations() []*AniDBRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *AniDBAnimeDetails) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AniDBAnimeDetails) GetCreators() []*AniDBCreator {
	if x != nil {
		return x.Creators
	}
	return nil
}

func (x *AniDBAnimeDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AniDBAnimeDetails) GetRatings() *AniDBRatings {
	if x != nil {
		return x.Ratings
	}
	return nil
}

func (x *AniDBAnimeDetails) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *AniDBAnimeDetails) GetResources() []*AniDBResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AniDBAnimeDetails) GetTags() []*AniDBTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AniDBAnimeDetails) GetEpisodes() []*AniDBAnimeEpisode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

func (x *AniDBAnimeDetails) GetCharacters() []*AniDBCharacter {
	if x != nil {
		return x.Characters
	}
	return nil
}

type AniDBMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Aid           uint64                 `protobuf:"varint,6,opt,name=aid,proto3" json:"aid,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBMedia) Reset() {
	*x = AniDBMedia{}
	mi := &file_anidb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBMedia) ProtoMessage() {}

func (x *AniDBMedia) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBMedia.ProtoReflect.Descriptor instead.
func (*AniDBMedia) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{21}
}

func (x *AniDBMedia) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AniDBMedia) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AniDBMedia) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AniDBMedia) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *AniDBMedia) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AniDBMedia) GetAid() uint64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *AniDBMedia) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

type AniDBDetailedEpisode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	DetailedId    uint64                 `protobuf:"varint,5,opt,name=detailed_id,json=detailedId,proto3" json:"detailed_id,omitempty"`
	AnidbId       string                 `protobuf:"bytes,6,opt,name=anidb_id,json=anidbId,proto3" json:"anidb_id,omitempty"`
	Type          int32                  `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	EpNo          string                 `protobuf:"bytes,8,opt,name=ep_no,json=epNo,proto3" json:"ep_no,omitempty"`
	Title         string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	AirDate       string                 `protobuf:"bytes,10,opt,name=air_date,json=airDate,proto3" json:"air_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AniDBDetailedEpisode) Reset() {
	*x = AniDBDetailedEpisode{}
	mi := &file_anidb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBDetailedEpisode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBDetailedEpisode) ProtoMessage() {}

func (x *AniDBDetailedEpisode) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBDetailedEpisode.ProtoReflect.Descriptor instead.
func (*AniDBDetailedEpisode) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{22}
}

func (x *AniDBDetailedEpisode) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AniDBDetailedEpisode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AniDBDetailedEpisode) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AniDBDetailedEpisode) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *AniDBDetailedEpisode) GetDetailedId() uint64 {
	if x != nil {
		return x.DetailedId
	}
	return 0
}

func (x *AniDBDetailedEpisode) GetAnidbId() string {
	if x != nil {
		return x.AnidbId
	}
	return ""
}

func (x *AniDBDetailedEpisode) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AniDBDetailedEpisode) GetEpNo() string {
	if x != nil {
		return x.EpNo
	}
	return ""
}

func (x *AniDBDetailedEpisode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AniDBDetailedEpisode) GetAirDate() string {
	if x != nil {
		return x.AirDate
	}
	return ""
}

type AniDBDetailed struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Title           string                  `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Aid             uint64                  `protobuf:"varint,6,opt,name=aid,proto3" json:"aid,omitempty"`
	LibraryId       uint64                  `protobuf:"varint,7,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	AlternateTitles string                  `protobuf:"bytes,8,opt,name=alternate_titles,json=alternateTitles,proto3" json:"alternate_titles,omitempty"`
	Description     string                  `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	ReleaseDate     string                  `protobuf:"bytes,10,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Genres          string                  `protobuf:"bytes,11,opt,name=genres,proto3" json:"genres,omitempty"`
	PosterUrl       string                  `protobuf:"bytes,12,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	TotalEpisodes   int32                   `protobuf:"varint,13,opt,name=total_episodes,json=totalEpisodes,proto3" json:"total_episodes,omitempty"`
	TotalSeasons    int32                   `protobuf:"varint,14,opt,name=total_seasons,json=totalSeasons,proto3" json:"total_seasons,omitempty"`
	Episodes        []*AniDBDetailedEpisode `protobuf:"bytes,15,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AniDBDetailed) Reset() {
	*x = AniDBDetailed{}
	mi := &file_anidb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AniDBDetailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniDBDetailed) ProtoMessage() {}

func (x *AniDBDetailed) ProtoReflect() protoreflect.Message {
	mi := &file_anidb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniDBDetailed.ProtoReflect.Descriptor instead.
func (*AniDBDetailed) Descriptor() ([]byte, []int) {
	return file_anidb_proto_rawDescGZIP(), []int{23}
}

func (x *AniDBDetailed) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AniDBDetailed) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AniDBDetailed) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AniDBDetailed) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *AniDBDetailed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AniDBDetailed) GetAid() uint64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *AniDBDetailed) GetLibraryId() uint64 {
	if x != nil {
		return x.LibraryId
	}
	return 0
}

func (x *AniDBDetailed) GetAlternateTitles() string {
	if x != nil {
		return x.AlternateTitles
	}
	return ""
}

func (x *AniDBDetailed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AniDBDetailed) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *AniDBDetailed) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *AniDBDetailed) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *AniDBDetailed) GetTotalEpisodes() int32 {
	if x != nil {
		return x.TotalEpisodes
	}
	return 0
}

func (x *AniDBDetailed) GetTotalSeasons() int32 {
	if x != nil {
		return x.TotalSeasons
	}
	return 0
}

func (x *AniDBDetailed) GetEpisodes() []*AniDBDetailedEpisode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

var File_anidb_proto protoreflect.FileDescriptor

const file_anidb_proto_rawDesc = "" +
	"\n" +
	"\vanidb.proto\x12\x05kbarr\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x18AniDBSearchTitlesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"Q\n" +
	"\x11AniDBSearchResult\x12\x10\n" +
	"\x03aid\x18\x01 \x01(\x04R\x03aid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05added\x18\x03 \x01(\bR\x05added\"O\n" +
	"\x19AniDBSearchTitlesResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.kbarr.AniDBSearchResultR\aresults\"/\n" +
	"\x1bAniDBGetAnimeDetailsRequest\x12\x10\n" +
	"\x03aid\x18\x01 \x01(\x04R\x03aid\"O\n" +
	"\x0fAniDBAnimeTitle\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"M\n" +
	"\x11AniDBRelatedAnime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"k\n" +
	"\x11AniDBSimilarAnime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bapproval\x18\x02 \x01(\tR\bapproval\x12\x14\n" +
	"\x05total\x18\x03 \x01(\tR\x05total\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"O\n" +
	"\x13AniDBRecommendation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"F\n" +
	"\fAniDBCreator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"=\n" +
	"\x0fAniDBVoteRating\x12\x14\n" +
	"\x05votes\x18\x01 \x01(\tR\x05votes\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\">\n" +
	"\x10AniDBCountRating\x12\x14\n" +
	"\x05count\x18\x01 \x01(\tR\x05count\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xad\x01\n" +
	"\fAniDBRatings\x125\n" +
	"\tpermanent\x18\x01 \x01(\v2\x17.kbarr.AniDBCountRatingR\tpermanent\x125\n" +
	"\ttemporary\x18\x02 \x01(\v2\x17.kbarr.AniDBCountRatingR\ttemporary\x12/\n" +
	"\x06review\x18\x03 \x01(\v2\x17.kbarr.AniDBCountRatingR\x06review\"O\n" +
	"\x1bAniDBResourceExternalEntity\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x03(\tR\n" +
	"identifier\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"p\n" +
	"\rAniDBResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12K\n" +
	"\x0fexternal_entity\x18\x02 \x01(\v2\".kbarr.AniDBResourceExternalEntityR\x0eexternalEntity\"\xb8\x02\n" +
	"\bAniDBTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\tR\x06weight\x12#\n" +
	"\rlocal_spoiler\x18\x04 \x01(\tR\flocalSpoiler\x12%\n" +
	"\x0eglobal_spoiler\x18\x05 \x01(\tR\rglobalSpoiler\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\tR\bverified\x12\x16\n" +
	"\x06update\x18\a \x01(\tR\x06update\x12\x18\n" +
	"\ainfobox\x18\b \x01(\tR\ainfobox\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x17\n" +
	"\apic_url\x18\v \x01(\tR\x06picUrl\"8\n" +
	"\x12AniDBCharacterType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"K\n" +
	"\vAniDBSeiyuu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apicture\x18\x02 \x01(\tR\apicture\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xd2\x02\n" +
	"\x0eAniDBCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06update\x18\x03 \x01(\tR\x06update\x12.\n" +
	"\x06rating\x18\x04 \x01(\v2\x16.kbarr.AniDBVoteRatingR\x06rating\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12@\n" +
	"\x0echaracter_type\x18\a \x01(\v2\x19.kbarr.AniDBCharacterTypeR\rcharacterType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\t \x01(\tR\apicture\x12*\n" +
	"\x06seiyuu\x18\n" +
	" \x03(\v2\x12.kbarr.AniDBSeiyuuR\x06seiyuu\">\n" +
	"\x12AniDBEpisodeNumber\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xfe\x01\n" +
	"\x11AniDBAnimeEpisode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06update\x18\x02 \x01(\tR\x06update\x12.\n" +
	"\x05ep_no\x18\x03 \x01(\v2\x19.kbarr.AniDBEpisodeNumberR\x04epNo\x12\x16\n" +
	"\x06length\x18\x04 \x01(\tR\x06length\x12\x19\n" +
	"\bair_date\x18\x05 \x01(\tR\aairDate\x12.\n" +
	"\x06rating\x18\x06 \x01(\v2\x16.kbarr.AniDBVoteRatingR\x06rating\x12.\n" +
	"\x06titles\x18\a \x03(\v2\x16.kbarr.AniDBAnimeTitleR\x06titles\"\xa0\x06\n" +
	"\x11AniDBAnimeDetails\x12\x10\n" +
	"\x03aid\x18\x01 \x01(\x04R\x03aid\x12\x1e\n" +
	"\n" +
	"restricted\x18\x02 \x01(\tR\n" +
	"restricted\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12#\n" +
	"\repisode_count\x18\x04 \x01(\x05R\fepisodeCount\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12.\n" +
	"\x06titles\x18\a \x03(\v2\x16.kbarr.AniDBAnimeTitleR\x06titles\x12=\n" +
	"\rrelated_anime\x18\b \x03(\v2\x18.kbarr.AniDBRelatedAnimeR\frelatedAnime\x12=\n" +
	"\rsimilar_anime\x18\t \x03(\v2\x18.kbarr.AniDBSimilarAnimeR\fsimilarAnime\x12D\n" +
	"\x0frecommendations\x18\n" +
	" \x03(\v2\x1a.kbarr.AniDBRecommendationR\x0frecommendations\x12\x10\n" +
	"\x03url\x18\v \x01(\tR\x03url\x12/\n" +
	"\bcreators\x18\f \x03(\v2\x13.kbarr.AniDBCreatorR\bcreators\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12-\n" +
	"\aratings\x18\x0e \x01(\v2\x13.kbarr.AniDBRatingsR\aratings\x12\x18\n" +
	"\apicture\x18\x0f \x01(\tR\apicture\x122\n" +
	"\tresources\x18\x10 \x03(\v2\x14.kbarr.AniDBResourceR\tresources\x12#\n" +
	"\x04tags\x18\x11 \x03(\v2\x0f.kbarr.AniDBTagR\x04tags\x124\n" +
	"\bepisodes\x18\x12 \x03(\v2\x18.kbarr.AniDBAnimeEpisodeR\bepisodes\x125\n" +
	"\n" +
	"characters\x18\x13 \x03(\v2\x15.kbarr.AniDBCharacterR\n" +
	"characters\"\x94\x02\n" +
	"\n" +
	"AniDBMedia\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x10\n" +
	"\x03aid\x18\x06 \x01(\x04R\x03aid\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\"\xed\x02\n" +
	"\x14AniDBDetailedEpisode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1f\n" +
	"\vdetailed_id\x18\x05 \x01(\x04R\n" +
	"detailedId\x12\x19\n" +
	"\banidb_id\x18\x06 \x01(\tR\aanidbId\x12\x12\n" +
	"\x04type\x18\a \x01(\x05R\x04type\x12\x13\n" +
	"\x05ep_no\x18\b \x01(\tR\x04epNo\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12\x19\n" +
	"\bair_date\x18\n" +
	" \x01(\tR\aairDate\"\xc3\x04\n" +
	"\rAniDBDetailed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x10\n" +
	"\x03aid\x18\x06 \x01(\x04R\x03aid\x12\x1d\n" +
	"\n" +
	"library_id\x18\a \x01(\x04R\tlibraryId\x12)\n" +
	"\x10alternate_titles\x18\b \x01(\tR\x0falternateTitles\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12!\n" +
	"\frelease_date\x18\n" +
	" \x01(\tR\vreleaseDate\x12\x16\n" +
	"\x06genres\x18\v \x01(\tR\x06genres\x12\x1d\n" +
	"\n" +
	"poster_url\x18\f \x01(\tR\tposterUrl\x12%\n" +
	"\x0etotal_episodes\x18\r \x01(\x05R\rtotalEpisodes\x12#\n" +
	"\rtotal_seasons\x18\x0e \x01(\x05R\ftotalSeasons\x127\n" +
	"\bepisodes\x18\x0f \x03(\v2\x1b.kbarr.AniDBDetailedEpisodeR\bepisodes2\xf7\x01\n" +
	"\fAniDBService\x12Q\n" +
	"\fSearchTitles\x12\x1f.kbarr.AniDBSearchTitlesRequest\x1a .kbarr.AniDBSearchTitlesResponse\x12O\n" +
	"\x0fGetAnimeDetails\x12\".kbarr.AniDBGetAnimeDetailsRequest\x1a\x18.kbarr.AniDBAnimeDetails\x12C\n" +
	"\x18PrepareDetailedFromMedia\x12\x11.kbarr.AniDBMedia\x1a\x14.kbarr.AniDBDetailedB2Z0github.com/kingbenny101/kbarr/shared/proto;protob\x06proto3"

var (
	file_anidb_proto_rawDescOnce sync.Once
	file_anidb_proto_rawDescData []byte
)

func file_anidb_proto_rawDescGZIP() []byte {
	file_anidb_proto_rawDescOnce.Do(func() {
		file_anidb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anidb_proto_rawDesc), len(file_anidb_proto_rawDesc)))
	})
	return file_anidb_proto_rawDescData
}

var file_anidb_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_anidb_proto_goTypes = []any{
	(*AniDBSearchTitlesRequest)(nil),    // 0: kbarr.AniDBSearchTitlesRequest
	(*AniDBSearchResult)(nil),           // 1: kbarr.AniDBSearchResult
	(*AniDBSearchTitlesResponse)(nil),   // 2: kbarr.AniDBSearchTitlesResponse
	(*AniDBGetAnimeDetailsRequest)(nil), // 3: kbarr.AniDBGetAnimeDetailsRequest
	(*AniDBAnimeTitle)(nil),             // 4: kbarr.AniDBAnimeTitle
	(*AniDBRelatedAnime)(nil),           // 5: kbarr.AniDBRelatedAnime
	(*AniDBSimilarAnime)(nil),           // 6: kbarr.AniDBSimilarAnime
	(*AniDBRecommendation)(nil),         // 7: kbarr.AniDBRecommendation
	(*AniDBCreator)(nil),                // 8: kbarr.AniDBCreator
	(*AniDBVoteRating)(nil),             // 9: kbarr.AniDBVoteRating
	(*AniDBCountRating)(nil),            // 10: kbarr.AniDBCountRating
	(*AniDBRatings)(nil),                // 11: kbarr.AniDBRatings
	(*AniDBResourceExternalEntity)(nil), // 12: kbarr.AniDBResourceExternalEntity
	(*AniDBResource)(nil),               // 13: kbarr.AniDBResource
	(*AniDBTag)(nil),                    // 14: kbarr.AniDBTag
	(*AniDBCharacterType)(nil),          // 15: kbarr.AniDBCharacterType
	(*AniDBSeiyuu)(nil),                 // 16: kbarr.AniDBSeiyuu
	(*AniDBCharacter)(nil),              // 17: kbarr.AniDBCharacter
	(*AniDBEpisodeNumber)(nil),          // 18: kbarr.AniDBEpisodeNumber
	(*AniDBAnimeEpisode)(nil),           // 19: kbarr.AniDBAnimeEpisode
	(*AniDBAnimeDetails)(nil),           // 20: kbarr.AniDBAnimeDetails
	(*AniDBMedia)(nil),                  // 21: kbarr.AniDBMedia
	(*AniDBDetailedEpisode)(nil),        // 22: kbarr.AniDBDetailedEpisode
	(*AniDBDetailed)(nil),               // 23: kbarr.AniDBDetailed
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
}
var file_anidb_proto_depIdxs = []int32{
	1,  // 0: kbarr.AniDBSearchTitlesResponse.results:type_name -> kbarr.AniDBSearchResult
	10, // 1: kbarr.AniDBRatings.permanent:type_name -> kbarr.AniDBCountRating
	10, // 2: kbarr.AniDBRatings.temporary:type_name -> kbarr.AniDBCountRating
	10, // 3: kbarr.AniDBRatings.review:type_name -> kbarr.AniDBCountRating
	12, // 4: kbarr.AniDBResource.external_entity:type_name -> kbarr.AniDBResourceExternalEntity
	9,  // 5: kbarr.AniDBCharacter.rating:type_name -> kbarr.AniDBVoteRating
	15, // 6: kbarr.AniDBCharacter.character_type:type_name -> kbarr.AniDBCharacterType
	16, // 7: kbarr.AniDBCharacter.seiyuu:type_name -> kbarr.AniDBSeiyuu
	18, // 8: kbarr.AniDBAnimeEpisode.ep_no:type_name -> kbarr.AniDBEpisodeNumber
	9,  // 9: kbarr.AniDBAnimeEpisode.rating:type_name -> kbarr.AniDBVoteRating
	4,  // 10: kbarr.AniDBAnimeEpisode.titles:type_name -> kbarr.AniDBAnimeTitle
	4,  // 11: kbarr.AniDBAnimeDetails.titles:type_name -> kbarr.AniDBAnimeTitle
	5,  // 12: kbarr.AniDBAnimeDetails.related_anime:type_name -> kbarr.AniDBRelatedAnime
	6,  // 13: kbarr.AniDBAnimeDetails.similar_anime:type_name -> kbarr.AniDBSimilarAnime
	7,  // 14: kbarr.AniDBAnimeDetails.recommendations:type_name -> kbarr.AniDBRecommendation
	8,  // 15: kbarr.AniDBAnimeDetails.creators:type_name -> kbarr.AniDBCreator
	11, // 16: kbarr.AniDBAnimeDetails.ratings:type_name -> kbarr.AniDBRatings
	13, // 17: kbarr.AniDBAnimeDetails.resources:type_name -> kbarr.AniDBResource
	14, // 18: kbarr.AniDBAnimeDetails.tags:type_name -> kbarr.AniDBTag
	19, // 19: kbarr.AniDBAnimeDetails.episodes:type_name -> kbarr.AniDBAnimeEpisode
	17, // 20: kbarr.AniDBAnimeDetails.characters:type_name -> kbarr.AniDBCharacter
	24, // 21: kbarr.AniDBMedia.created_at:type_name -> google.protobuf.Timestamp
	24, // 22: kbarr.AniDBMedia.updated_at:type_name -> google.protobuf.Timestamp
	24, // 23: kbarr.AniDBMedia.deleted_at:type_name -> google.protobuf.Timestamp
	24, // 24: kbarr.AniDBDetailedEpisode.created_at:type_name -> google.protobuf.Timestamp
	24, // 25: kbarr.AniDBDetailedEpisode.updated_at:type_name -> google.protobuf.Timestamp
	24, // 26: kbarr.AniDBDetailedEpisode.deleted_at:type_name -> google.protobuf.Timestamp
	24, // 27: kbarr.AniDBDetailed.created_at:type_name -> google.protobuf.Timestamp
	24, // 28: kbarr.AniDBDetailed.updated_at:type_name -> google.protobuf.Timestamp
	24, // 29: kbarr.AniDBDetailed.deleted_at:type_name -> google.protobuf.Timestamp
	22, // 30: kbarr.AniDBDetailed.episodes:type_name -> kbarr.AniDBDetailedEpisode
	0,  // 31: kbarr.AniDBService.SearchTitles:input_type -> kbarr.AniDBSearchTitlesRequest
	3,  // 32: kbarr.AniDBService.GetAnimeDetails:input_type -> kbarr.AniDBGetAnimeDetailsRequest
	21, // 33: kbarr.AniDBService.PrepareDetailedFromMedia:input_type -> kbarr.AniDBMedia
	2,  // 34: kbarr.AniDBService.SearchTitles:output_type -> kbarr.AniDBSearchTitlesResponse
	20, // 35: kbarr.AniDBService.GetAnimeDetails:output_type -> kbarr.AniDBAnimeDetails
	23, // 36: kbarr.AniDBService.PrepareDetailedFromMedia:output_type -> kbarr.AniDBDetailed
	34, // [34:37] is the sub-list for method output_type
	31, // [31:34] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_anidb_proto_init() }
func file_anidb_proto_init() {
	if File_anidb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anidb_proto_rawDesc), len(file_anidb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anidb_proto_goTypes,
		DependencyIndexes: file_anidb_proto_depIdxs,
		MessageInfos:      file_anidb_proto_msgTypes,
	}.Build()
	File_anidb_proto = out.File
	file_anidb_proto_goTypes = nil
	file_anidb_proto_depIdxs = nil
}
