// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: downloader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MagnetUrl     string                 `protobuf:"bytes,1,opt,name=magnet_url,json=magnetUrl,proto3" json:"magnet_url,omitempty"`
	SavePath      string                 `protobuf:"bytes,2,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTorrentRequest) Reset() {
	*x = AddTorrentRequest{}
	mi := &file_downloader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTorrentRequest) ProtoMessage() {}

func (x *AddTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTorrentRequest.ProtoReflect.Descriptor instead.
func (*AddTorrentRequest) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{0}
}

func (x *AddTorrentRequest) GetMagnetUrl() string {
	if x != nil {
		return x.MagnetUrl
	}
	return ""
}

func (x *AddTorrentRequest) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *AddTorrentRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AddTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTorrentResponse) Reset() {
	*x = AddTorrentResponse{}
	mi := &file_downloader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTorrentResponse) ProtoMessage() {}

func (x *AddTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTorrentResponse.ProtoReflect.Descriptor instead.
func (*AddTorrentResponse) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{1}
}

func (x *AddTorrentResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *AddTorrentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddTorrentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentRequest) Reset() {
	*x = TorrentRequest{}
	mi := &file_downloader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentRequest) ProtoMessage() {}

func (x *TorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentRequest.ProtoReflect.Descriptor instead.
func (*TorrentRequest) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{2}
}

func (x *TorrentRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type TorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Progress      float32                `protobuf:"fixed32,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Eta           int64                  `protobuf:"varint,6,opt,name=eta,proto3" json:"eta,omitempty"`
	SavePath      string                 `protobuf:"bytes,7,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	Category      string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentResponse) Reset() {
	*x = TorrentResponse{}
	mi := &file_downloader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentResponse) ProtoMessage() {}

func (x *TorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentResponse.ProtoReflect.Descriptor instead.
func (*TorrentResponse) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{3}
}

func (x *TorrentResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TorrentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TorrentResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TorrentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TorrentResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TorrentResponse) GetEta() int64 {
	if x != nil {
		return x.Eta
	}
	return 0
}

func (x *TorrentResponse) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *TorrentResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListTorrentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTorrentsRequest) Reset() {
	*x = ListTorrentsRequest{}
	mi := &file_downloader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTorrentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTorrentsRequest) ProtoMessage() {}

func (x *ListTorrentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTorrentsRequest.ProtoReflect.Descriptor instead.
func (*ListTorrentsRequest) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{4}
}

func (x *ListTorrentsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListTorrentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrents      []*TorrentResponse     `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTorrentsResponse) Reset() {
	*x = ListTorrentsResponse{}
	mi := &file_downloader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTorrentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTorrentsResponse) ProtoMessage() {}

func (x *ListTorrentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTorrentsResponse.ProtoReflect.Descriptor instead.
func (*ListTorrentsResponse) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{5}
}

func (x *ListTorrentsResponse) GetTorrents() []*TorrentResponse {
	if x != nil {
		return x.Torrents
	}
	return nil
}

type RemoveTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	DeleteFiles   bool                   `protobuf:"varint,2,opt,name=delete_files,json=deleteFiles,proto3" json:"delete_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTorrentRequest) Reset() {
	*x = RemoveTorrentRequest{}
	mi := &file_downloader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTorrentRequest) ProtoMessage() {}

func (x *RemoveTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTorrentRequest.ProtoReflect.Descriptor instead.
func (*RemoveTorrentRequest) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveTorrentRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *RemoveTorrentRequest) GetDeleteFiles() bool {
	if x != nil {
		return x.DeleteFiles
	}
	return false
}

type RemoveTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTorrentResponse) Reset() {
	*x = RemoveTorrentResponse{}
	mi := &file_downloader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTorrentResponse) ProtoMessage() {}

func (x *RemoveTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTorrentResponse.ProtoReflect.Descriptor instead.
func (*RemoveTorrentResponse) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveTorrentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveTorrentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_downloader_proto protoreflect.FileDescriptor

const file_downloader_proto_rawDesc = "" +
	"\n" +
	"\x10downloader.proto\x12\n" +
	"downloader\"k\n" +
	"\x11AddTorrentRequest\x12\x1d\n" +
	"\n" +
	"magnet_url\x18\x01 \x01(\tR\tmagnetUrl\x12\x1b\n" +
	"\tsave_path\x18\x02 \x01(\tR\bsavePath\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"X\n" +
	"\x12AddTorrentResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"$\n" +
	"\x0eTorrentRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xca\x01\n" +
	"\x0fTorrentResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x02R\bprogress\x12\x10\n" +
	"\x03eta\x18\x06 \x01(\x03R\x03eta\x12\x1b\n" +
	"\tsave_path\x18\a \x01(\tR\bsavePath\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\"1\n" +
	"\x13ListTorrentsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"O\n" +
	"\x14ListTorrentsResponse\x127\n" +
	"\btorrents\x18\x01 \x03(\v2\x1b.downloader.TorrentResponseR\btorrents\"M\n" +
	"\x14RemoveTorrentRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12!\n" +
	"\fdelete_files\x18\x02 \x01(\bR\vdeleteFiles\"G\n" +
	"\x15RemoveTorrentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xc9\x02\n" +
	"\n" +
	"Downloader\x12K\n" +
	"\n" +
	"AddTorrent\x12\x1d.downloader.AddTorrentRequest\x1a\x1e.downloader.AddTorrentResponse\x12E\n" +
	"\n" +
	"GetTorrent\x12\x1a.downloader.TorrentRequest\x1a\x1b.downloader.TorrentResponse\x12Q\n" +
	"\fListTorrents\x12\x1f.downloader.ListTorrentsRequest\x1a .downloader.ListTorrentsResponse\x12T\n" +
	"\rRemoveTorrent\x12 .downloader.RemoveTorrentRequest\x1a!.downloader.RemoveTorrentResponseB\x1fZ\x1dkbarr/shared/proto/downloaderb\x06proto3"

var (
	file_downloader_proto_rawDescOnce sync.Once
	file_downloader_proto_rawDescData []byte
)

func file_downloader_proto_rawDescGZIP() []byte {
	file_downloader_proto_rawDescOnce.Do(func() {
		file_downloader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_downloader_proto_rawDesc), len(file_downloader_proto_rawDesc)))
	})
	return file_downloader_proto_rawDescData
}

var file_downloader_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_downloader_proto_goTypes = []any{
	(*AddTorrentRequest)(nil),     // 0: downloader.AddTorrentRequest
	(*AddTorrentResponse)(nil),    // 1: downloader.AddTorrentResponse
	(*TorrentRequest)(nil),        // 2: downloader.TorrentRequest
	(*TorrentResponse)(nil),       // 3: downloader.TorrentResponse
	(*ListTorrentsRequest)(nil),   // 4: downloader.ListTorrentsRequest
	(*ListTorrentsResponse)(nil),  // 5: downloader.ListTorrentsResponse
	(*RemoveTorrentRequest)(nil),  // 6: downloader.RemoveTorrentRequest
	(*RemoveTorrentResponse)(nil), // 7: downloader.RemoveTorrentResponse
}
var file_downloader_proto_depIdxs = []int32{
	3, // 0: downloader.ListTorrentsResponse.torrents:type_name -> downloader.TorrentResponse
	0, // 1: downloader.Downloader.AddTorrent:input_type -> downloader.AddTorrentRequest
	2, // 2: downloader.Downloader.GetTorrent:input_type -> downloader.TorrentRequest
	4, // 3: downloader.Downloader.ListTorrents:input_type -> downloader.ListTorrentsRequest
	6, // 4: downloader.Downloader.RemoveTorrent:input_type -> downloader.RemoveTorrentRequest
	1, // 5: downloader.Downloader.AddTorrent:output_type -> downloader.AddTorrentResponse
	3, // 6: downloader.Downloader.GetTorrent:output_type -> downloader.TorrentResponse
	5, // 7: downloader.Downloader.ListTorrents:output_type -> downloader.ListTorrentsResponse
	7, // 8: downloader.Downloader.RemoveTorrent:output_type -> downloader.RemoveTorrentResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_downloader_proto_init() }
func file_downloader_proto_init() {
	if File_downloader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_downloader_proto_rawDesc), len(file_downloader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_downloader_proto_goTypes,
		DependencyIndexes: file_downloader_proto_depIdxs,
		MessageInfos:      file_downloader_proto_msgTypes,
	}.Build()
	File_downloader_proto = out.File
	file_downloader_proto_goTypes = nil
	file_downloader_proto_depIdxs = nil
}
