syntax = "proto3";

package indexer;

option go_package = "github.com/kingbenny101/kbarr/shared/proto/indexer;indexer";

service IndexerService {
  rpc Search(ProwlarrSearchRequest) returns (ProwlarrSearchResponse);
}

message ProwlarrSearchRequest {
  string query = 1;
}

message ProwlarrSearchResult {
  string title = 1;
  string download_url = 2;
  int64 size = 3;
  string indexer = 4;
  int32 seeds = 5;
  int32 peers = 6;
}

message ProwlarrSearchResponse {
  repeated ProwlarrSearchResult results = 1;
}