// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: prowlarr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProwlarrService_Search_FullMethodName = "/kbarr.ProwlarrService/Search"
)

// ProwlarrServiceClient is the client API for ProwlarrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProwlarrServiceClient interface {
	Search(ctx context.Context, in *ProwlarrSearchRequest, opts ...grpc.CallOption) (*ProwlarrSearchResponse, error)
}

type prowlarrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProwlarrServiceClient(cc grpc.ClientConnInterface) ProwlarrServiceClient {
	return &prowlarrServiceClient{cc}
}

func (c *prowlarrServiceClient) Search(ctx context.Context, in *ProwlarrSearchRequest, opts ...grpc.CallOption) (*ProwlarrSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProwlarrSearchResponse)
	err := c.cc.Invoke(ctx, ProwlarrService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProwlarrServiceServer is the server API for ProwlarrService service.
// All implementations must embed UnimplementedProwlarrServiceServer
// for forward compatibility.
type ProwlarrServiceServer interface {
	Search(context.Context, *ProwlarrSearchRequest) (*ProwlarrSearchResponse, error)
	mustEmbedUnimplementedProwlarrServiceServer()
}

// UnimplementedProwlarrServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProwlarrServiceServer struct{}

func (UnimplementedProwlarrServiceServer) Search(context.Context, *ProwlarrSearchRequest) (*ProwlarrSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedProwlarrServiceServer) mustEmbedUnimplementedProwlarrServiceServer() {}
func (UnimplementedProwlarrServiceServer) testEmbeddedByValue()                         {}

// UnsafeProwlarrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProwlarrServiceServer will
// result in compilation errors.
type UnsafeProwlarrServiceServer interface {
	mustEmbedUnimplementedProwlarrServiceServer()
}

func RegisterProwlarrServiceServer(s grpc.ServiceRegistrar, srv ProwlarrServiceServer) {
	// If the following call panics, it indicates UnimplementedProwlarrServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProwlarrService_ServiceDesc, srv)
}

func _ProwlarrService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProwlarrSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProwlarrServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProwlarrService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProwlarrServiceServer).Search(ctx, req.(*ProwlarrSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProwlarrService_ServiceDesc is the grpc.ServiceDesc for ProwlarrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProwlarrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kbarr.ProwlarrService",
	HandlerType: (*ProwlarrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _ProwlarrService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prowlarr.proto",
}
