// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: metadata.proto

package metadata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_SearchTitles_FullMethodName             = "/metadata.MetadataService/SearchTitles"
	MetadataService_GetAnimeDetails_FullMethodName          = "/metadata.MetadataService/GetAnimeDetails"
	MetadataService_PrepareDetailedFromMedia_FullMethodName = "/metadata.MetadataService/PrepareDetailedFromMedia"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataServiceClient interface {
	SearchTitles(ctx context.Context, in *AniDBSearchTitlesRequest, opts ...grpc.CallOption) (*AniDBSearchTitlesResponse, error)
	GetAnimeDetails(ctx context.Context, in *AniDBGetAnimeDetailsRequest, opts ...grpc.CallOption) (*AniDBAnimeDetails, error)
	PrepareDetailedFromMedia(ctx context.Context, in *AniDBMedia, opts ...grpc.CallOption) (*AniDBDetailed, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) SearchTitles(ctx context.Context, in *AniDBSearchTitlesRequest, opts ...grpc.CallOption) (*AniDBSearchTitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AniDBSearchTitlesResponse)
	err := c.cc.Invoke(ctx, MetadataService_SearchTitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetAnimeDetails(ctx context.Context, in *AniDBGetAnimeDetailsRequest, opts ...grpc.CallOption) (*AniDBAnimeDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AniDBAnimeDetails)
	err := c.cc.Invoke(ctx, MetadataService_GetAnimeDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) PrepareDetailedFromMedia(ctx context.Context, in *AniDBMedia, opts ...grpc.CallOption) (*AniDBDetailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AniDBDetailed)
	err := c.cc.Invoke(ctx, MetadataService_PrepareDetailedFromMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
type MetadataServiceServer interface {
	SearchTitles(context.Context, *AniDBSearchTitlesRequest) (*AniDBSearchTitlesResponse, error)
	GetAnimeDetails(context.Context, *AniDBGetAnimeDetailsRequest) (*AniDBAnimeDetails, error)
	PrepareDetailedFromMedia(context.Context, *AniDBMedia) (*AniDBDetailed, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) SearchTitles(context.Context, *AniDBSearchTitlesRequest) (*AniDBSearchTitlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTitles not implemented")
}
func (UnimplementedMetadataServiceServer) GetAnimeDetails(context.Context, *AniDBGetAnimeDetailsRequest) (*AniDBAnimeDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnimeDetails not implemented")
}
func (UnimplementedMetadataServiceServer) PrepareDetailedFromMedia(context.Context, *AniDBMedia) (*AniDBDetailed, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareDetailedFromMedia not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_SearchTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AniDBSearchTitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SearchTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_SearchTitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SearchTitles(ctx, req.(*AniDBSearchTitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetAnimeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AniDBGetAnimeDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetAnimeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetAnimeDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetAnimeDetails(ctx, req.(*AniDBGetAnimeDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_PrepareDetailedFromMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AniDBMedia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).PrepareDetailedFromMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_PrepareDetailedFromMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).PrepareDetailedFromMedia(ctx, req.(*AniDBMedia))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchTitles",
			Handler:    _MetadataService_SearchTitles_Handler,
		},
		{
			MethodName: "GetAnimeDetails",
			Handler:    _MetadataService_GetAnimeDetails_Handler,
		},
		{
			MethodName: "PrepareDetailedFromMedia",
			Handler:    _MetadataService_PrepareDetailedFromMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata.proto",
}
