FROM golang:1.25-alpine

WORKDIR /workspace
RUN apk add --no-cache ca-certificates

COPY shared ./shared
COPY services/anidb ./services/anidb

WORKDIR /workspace/services/anidb
RUN go mod download

EXPOSE 8081
CMD ["go", "run", "./cmd"]
