site_name: kbarr
site_description: Take lite
site_author: KingBenny101
site_url: https://kingbenny101.github.io/kbarr/
repo_url: https://github.com/KingBenny101/kbarr
repo_name: KingBenny101/kbarr

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  icon:
    logo: material/play-circle
    repo: fontawesome/brands/github

plugins:
  - search
  - blog:
      blog_dir: blog
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KingBenny101

nav:
  - About: index.md
  - Installation: installation.md
  - Documentation:
      - API Reference:
          - System: api/system.md
          - Auth: api/auth.md
          - Library: api/library.md
          - Monitor: api/monitor.md
          - Search: api/search.md
          - Downloads: api/downloads.md
          - Settings: api/settings.md
  - Blog: blog/index.md
