// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: downloader.proto

package downloader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Downloader_AddTorrent_FullMethodName    = "/downloader.Downloader/AddTorrent"
	Downloader_GetTorrent_FullMethodName    = "/downloader.Downloader/GetTorrent"
	Downloader_ListTorrents_FullMethodName  = "/downloader.Downloader/ListTorrents"
	Downloader_RemoveTorrent_FullMethodName = "/downloader.Downloader/RemoveTorrent"
)

// DownloaderClient is the client API for Downloader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DownloaderClient interface {
	AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*AddTorrentResponse, error)
	GetTorrent(ctx context.Context, in *TorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error)
	ListTorrents(ctx context.Context, in *ListTorrentsRequest, opts ...grpc.CallOption) (*ListTorrentsResponse, error)
	RemoveTorrent(ctx context.Context, in *RemoveTorrentRequest, opts ...grpc.CallOption) (*RemoveTorrentResponse, error)
}

type downloaderClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloaderClient(cc grpc.ClientConnInterface) DownloaderClient {
	return &downloaderClient{cc}
}

func (c *downloaderClient) AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*AddTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTorrentResponse)
	err := c.cc.Invoke(ctx, Downloader_AddTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloaderClient) GetTorrent(ctx context.Context, in *TorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TorrentResponse)
	err := c.cc.Invoke(ctx, Downloader_GetTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloaderClient) ListTorrents(ctx context.Context, in *ListTorrentsRequest, opts ...grpc.CallOption) (*ListTorrentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTorrentsResponse)
	err := c.cc.Invoke(ctx, Downloader_ListTorrents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloaderClient) RemoveTorrent(ctx context.Context, in *RemoveTorrentRequest, opts ...grpc.CallOption) (*RemoveTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTorrentResponse)
	err := c.cc.Invoke(ctx, Downloader_RemoveTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloaderServer is the server API for Downloader service.
// All implementations must embed UnimplementedDownloaderServer
// for forward compatibility.
type DownloaderServer interface {
	AddTorrent(context.Context, *AddTorrentRequest) (*AddTorrentResponse, error)
	GetTorrent(context.Context, *TorrentRequest) (*TorrentResponse, error)
	ListTorrents(context.Context, *ListTorrentsRequest) (*ListTorrentsResponse, error)
	RemoveTorrent(context.Context, *RemoveTorrentRequest) (*RemoveTorrentResponse, error)
	mustEmbedUnimplementedDownloaderServer()
}

// UnimplementedDownloaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDownloaderServer struct{}

func (UnimplementedDownloaderServer) AddTorrent(context.Context, *AddTorrentRequest) (*AddTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTorrent not implemented")
}
func (UnimplementedDownloaderServer) GetTorrent(context.Context, *TorrentRequest) (*TorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTorrent not implemented")
}
func (UnimplementedDownloaderServer) ListTorrents(context.Context, *ListTorrentsRequest) (*ListTorrentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTorrents not implemented")
}
func (UnimplementedDownloaderServer) RemoveTorrent(context.Context, *RemoveTorrentRequest) (*RemoveTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTorrent not implemented")
}
func (UnimplementedDownloaderServer) mustEmbedUnimplementedDownloaderServer() {}
func (UnimplementedDownloaderServer) testEmbeddedByValue()                    {}

// UnsafeDownloaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloaderServer will
// result in compilation errors.
type UnsafeDownloaderServer interface {
	mustEmbedUnimplementedDownloaderServer()
}

func RegisterDownloaderServer(s grpc.ServiceRegistrar, srv DownloaderServer) {
	// If the following call panics, it indicates UnimplementedDownloaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Downloader_ServiceDesc, srv)
}

func _Downloader_AddTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServer).AddTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Downloader_AddTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServer).AddTorrent(ctx, req.(*AddTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Downloader_GetTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServer).GetTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Downloader_GetTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServer).GetTorrent(ctx, req.(*TorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Downloader_ListTorrents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTorrentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServer).ListTorrents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Downloader_ListTorrents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServer).ListTorrents(ctx, req.(*ListTorrentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Downloader_RemoveTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServer).RemoveTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Downloader_RemoveTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServer).RemoveTorrent(ctx, req.(*RemoveTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Downloader_ServiceDesc is the grpc.ServiceDesc for Downloader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Downloader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downloader.Downloader",
	HandlerType: (*DownloaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTorrent",
			Handler:    _Downloader_AddTorrent_Handler,
		},
		{
			MethodName: "GetTorrent",
			Handler:    _Downloader_GetTorrent_Handler,
		},
		{
			MethodName: "ListTorrents",
			Handler:    _Downloader_ListTorrents_Handler,
		},
		{
			MethodName: "RemoveTorrent",
			Handler:    _Downloader_RemoveTorrent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "downloader.proto",
}
