// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: indexer.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProwlarrSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProwlarrSearchRequest) Reset() {
	*x = ProwlarrSearchRequest{}
	mi := &file_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProwlarrSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProwlarrSearchRequest) ProtoMessage() {}

func (x *ProwlarrSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProwlarrSearchRequest.ProtoReflect.Descriptor instead.
func (*ProwlarrSearchRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *ProwlarrSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ProwlarrSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Indexer       string                 `protobuf:"bytes,4,opt,name=indexer,proto3" json:"indexer,omitempty"`
	Seeds         int32                  `protobuf:"varint,5,opt,name=seeds,proto3" json:"seeds,omitempty"`
	Peers         int32                  `protobuf:"varint,6,opt,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProwlarrSearchResult) Reset() {
	*x = ProwlarrSearchResult{}
	mi := &file_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProwlarrSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProwlarrSearchResult) ProtoMessage() {}

func (x *ProwlarrSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProwlarrSearchResult.ProtoReflect.Descriptor instead.
func (*ProwlarrSearchResult) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *ProwlarrSearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProwlarrSearchResult) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ProwlarrSearchResult) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProwlarrSearchResult) GetIndexer() string {
	if x != nil {
		return x.Indexer
	}
	return ""
}

func (x *ProwlarrSearchResult) GetSeeds() int32 {
	if x != nil {
		return x.Seeds
	}
	return 0
}

func (x *ProwlarrSearchResult) GetPeers() int32 {
	if x != nil {
		return x.Peers
	}
	return 0
}

type ProwlarrSearchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*ProwlarrSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProwlarrSearchResponse) Reset() {
	*x = ProwlarrSearchResponse{}
	mi := &file_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProwlarrSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProwlarrSearchResponse) ProtoMessage() {}

func (x *ProwlarrSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProwlarrSearchResponse.ProtoReflect.Descriptor instead.
func (*ProwlarrSearchResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *ProwlarrSearchResponse) GetResults() []*ProwlarrSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_indexer_proto protoreflect.FileDescriptor

const file_indexer_proto_rawDesc = "" +
	"\n" +
	"\rindexer.proto\x12\aindexer\"-\n" +
	"\x15ProwlarrSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\xa9\x01\n" +
	"\x14ProwlarrSearchResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x18\n" +
	"\aindexer\x18\x04 \x01(\tR\aindexer\x12\x14\n" +
	"\x05seeds\x18\x05 \x01(\x05R\x05seeds\x12\x14\n" +
	"\x05peers\x18\x06 \x01(\x05R\x05peers\"Q\n" +
	"\x16ProwlarrSearchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.indexer.ProwlarrSearchResultR\aresults2[\n" +
	"\x0eIndexerService\x12I\n" +
	"\x06Search\x12\x1e.indexer.ProwlarrSearchRequest\x1a\x1f.indexer.ProwlarrSearchResponseB<Z:github.com/kingbenny101/kbarr/shared/proto/indexer;indexerb\x06proto3"

var (
	file_indexer_proto_rawDescOnce sync.Once
	file_indexer_proto_rawDescData []byte
)

func file_indexer_proto_rawDescGZIP() []byte {
	file_indexer_proto_rawDescOnce.Do(func() {
		file_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)))
	})
	return file_indexer_proto_rawDescData
}

var file_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_indexer_proto_goTypes = []any{
	(*ProwlarrSearchRequest)(nil),  // 0: indexer.ProwlarrSearchRequest
	(*ProwlarrSearchResult)(nil),   // 1: indexer.ProwlarrSearchResult
	(*ProwlarrSearchResponse)(nil), // 2: indexer.ProwlarrSearchResponse
}
var file_indexer_proto_depIdxs = []int32{
	1, // 0: indexer.ProwlarrSearchResponse.results:type_name -> indexer.ProwlarrSearchResult
	0, // 1: indexer.IndexerService.Search:input_type -> indexer.ProwlarrSearchRequest
	2, // 2: indexer.IndexerService.Search:output_type -> indexer.ProwlarrSearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_indexer_proto_init() }
func file_indexer_proto_init() {
	if File_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexer_proto_goTypes,
		DependencyIndexes: file_indexer_proto_depIdxs,
		MessageInfos:      file_indexer_proto_msgTypes,
	}.Build()
	File_indexer_proto = out.File
	file_indexer_proto_goTypes = nil
	file_indexer_proto_depIdxs = nil
}
