FROM golang:1.25-alpine

WORKDIR /workspace
RUN apk add --no-cache ca-certificates

COPY shared ./shared
COPY services/prowlarr ./services/prowlarr

WORKDIR /workspace/services/prowlarr
RUN go mod download

EXPOSE 8082
CMD ["go", "run", "./cmd"]
