import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

let apiSidebarItems: unknown[] = [];
try {
  // Generated by: npm run gen-api-docs
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  apiSidebarItems = require('./docs/api/sidebar.js');
} catch {
  // spec not yet generated — run: make gen-spec && npm run gen-api-docs
}

const sidebars: SidebarsConfig = {
  docs: [
    'installation',
    'internals',
  ],
  api: [
    {
      type: 'category',
      label: 'kbarr API',
      link: { type: 'generated-index', title: 'kbarr API Reference' },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      items: apiSidebarItems as any,
    },
  ],
};

export default sidebars;
